server:
  port: 8761


spring:
  profiles: peer1
  application:
    name: server-peer1
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8769/eureka/