server:
  port: 8769


spring:
  profiles: peer2
  application:
    name: server-peer2
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8769/eureka/